- name: Install repo PostgreSQL
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Install PostgreSQL
  yum:
    name: postgresql11-server
    state: present

- name: Initializing database
  shell: |
    /usr/pgsql-11/bin/postgresql-11-setup initdb

- name:
  systemd:
    name: postgresql-11
    enabled: yes
    state: started

#- name:
#  firewalld:

#firewall-cmd --get-active-zones
#firewall-cmd --zone=public --add-port=5432/tcp --permanent
#firewall-cmd --reload
#setsebool -P httpd_can_network_connect_db 1
